export const ADD_PRODUCTS = 'ADD_PRODUCTS'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'

export const ADD_CATEGORIES = 'ADD_CATEGORIES'
export const REMOVE_PRODUCT_CATEGORIES = 'REMOVE_PRODUCT_CATEGORIES'
export const ADD_PRODUCT_CATEGORIES = 'ADD_PRODUCT_CATEGORIES'

export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART'
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART'
export const REMOVE_ALL_PRODUCT_CART = 'REMOVE_ALL_PRODUCT_CART'
